/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellTrendsRouteImport } from './routes/_shell.trends'
import { Route as ShellTraceabilityRouteImport } from './routes/_shell.traceability'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellPlantPerformanceRouteImport } from './routes/_shell.plant-performance'
import { Route as ShellPlanVsActualRouteImport } from './routes/_shell.plan-vs-actual'
import { Route as ShellOverviewRouteImport } from './routes/_shell.overview'
import { Route as ShellMapRouteImport } from './routes/_shell.map'
import { Route as ShellLeaderboardRouteImport } from './routes/_shell.leaderboard'
import { Route as ShellGapRecoveryRouteImport } from './routes/_shell.gap-recovery'
import { Route as ShellAttainmentMatrixRouteImport } from './routes/_shell.attainment-matrix'
import { Route as ShellAiInsightsRouteImport } from './routes/_shell.ai-insights'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellTrendsRoute = ShellTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTraceabilityRoute = ShellTraceabilityRouteImport.update({
  id: '/traceability',
  path: '/traceability',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPlantPerformanceRoute = ShellPlantPerformanceRouteImport.update({
  id: '/plant-performance',
  path: '/plant-performance',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPlanVsActualRoute = ShellPlanVsActualRouteImport.update({
  id: '/plan-vs-actual',
  path: '/plan-vs-actual',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOverviewRoute = ShellOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMapRoute = ShellMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLeaderboardRoute = ShellLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellGapRecoveryRoute = ShellGapRecoveryRouteImport.update({
  id: '/gap-recovery',
  path: '/gap-recovery',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAttainmentMatrixRoute = ShellAttainmentMatrixRouteImport.update({
  id: '/attainment-matrix',
  path: '/attainment-matrix',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAiInsightsRoute = ShellAiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-insights': typeof ShellAiInsightsRoute
  '/attainment-matrix': typeof ShellAttainmentMatrixRoute
  '/gap-recovery': typeof ShellGapRecoveryRoute
  '/leaderboard': typeof ShellLeaderboardRoute
  '/map': typeof ShellMapRoute
  '/overview': typeof ShellOverviewRoute
  '/plan-vs-actual': typeof ShellPlanVsActualRoute
  '/plant-performance': typeof ShellPlantPerformanceRoute
  '/settings': typeof ShellSettingsRoute
  '/traceability': typeof ShellTraceabilityRoute
  '/trends': typeof ShellTrendsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-insights': typeof ShellAiInsightsRoute
  '/attainment-matrix': typeof ShellAttainmentMatrixRoute
  '/gap-recovery': typeof ShellGapRecoveryRoute
  '/leaderboard': typeof ShellLeaderboardRoute
  '/map': typeof ShellMapRoute
  '/overview': typeof ShellOverviewRoute
  '/plan-vs-actual': typeof ShellPlanVsActualRoute
  '/plant-performance': typeof ShellPlantPerformanceRoute
  '/settings': typeof ShellSettingsRoute
  '/traceability': typeof ShellTraceabilityRoute
  '/trends': typeof ShellTrendsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/ai-insights': typeof ShellAiInsightsRoute
  '/_shell/attainment-matrix': typeof ShellAttainmentMatrixRoute
  '/_shell/gap-recovery': typeof ShellGapRecoveryRoute
  '/_shell/leaderboard': typeof ShellLeaderboardRoute
  '/_shell/map': typeof ShellMapRoute
  '/_shell/overview': typeof ShellOverviewRoute
  '/_shell/plan-vs-actual': typeof ShellPlanVsActualRoute
  '/_shell/plant-performance': typeof ShellPlantPerformanceRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/traceability': typeof ShellTraceabilityRoute
  '/_shell/trends': typeof ShellTrendsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ai-insights'
    | '/attainment-matrix'
    | '/gap-recovery'
    | '/leaderboard'
    | '/map'
    | '/overview'
    | '/plan-vs-actual'
    | '/plant-performance'
    | '/settings'
    | '/traceability'
    | '/trends'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ai-insights'
    | '/attainment-matrix'
    | '/gap-recovery'
    | '/leaderboard'
    | '/map'
    | '/overview'
    | '/plan-vs-actual'
    | '/plant-performance'
    | '/settings'
    | '/traceability'
    | '/trends'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/login'
    | '/_shell/ai-insights'
    | '/_shell/attainment-matrix'
    | '/_shell/gap-recovery'
    | '/_shell/leaderboard'
    | '/_shell/map'
    | '/_shell/overview'
    | '/_shell/plan-vs-actual'
    | '/_shell/plant-performance'
    | '/_shell/settings'
    | '/_shell/traceability'
    | '/_shell/trends'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/trends': {
      id: '/_shell/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof ShellTrendsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/traceability': {
      id: '/_shell/traceability'
      path: '/traceability'
      fullPath: '/traceability'
      preLoaderRoute: typeof ShellTraceabilityRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/plant-performance': {
      id: '/_shell/plant-performance'
      path: '/plant-performance'
      fullPath: '/plant-performance'
      preLoaderRoute: typeof ShellPlantPerformanceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/plan-vs-actual': {
      id: '/_shell/plan-vs-actual'
      path: '/plan-vs-actual'
      fullPath: '/plan-vs-actual'
      preLoaderRoute: typeof ShellPlanVsActualRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/overview': {
      id: '/_shell/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof ShellOverviewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/map': {
      id: '/_shell/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof ShellMapRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/leaderboard': {
      id: '/_shell/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof ShellLeaderboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/gap-recovery': {
      id: '/_shell/gap-recovery'
      path: '/gap-recovery'
      fullPath: '/gap-recovery'
      preLoaderRoute: typeof ShellGapRecoveryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/attainment-matrix': {
      id: '/_shell/attainment-matrix'
      path: '/attainment-matrix'
      fullPath: '/attainment-matrix'
      preLoaderRoute: typeof ShellAttainmentMatrixRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/ai-insights': {
      id: '/_shell/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof ShellAiInsightsRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAiInsightsRoute: typeof ShellAiInsightsRoute
  ShellAttainmentMatrixRoute: typeof ShellAttainmentMatrixRoute
  ShellGapRecoveryRoute: typeof ShellGapRecoveryRoute
  ShellLeaderboardRoute: typeof ShellLeaderboardRoute
  ShellMapRoute: typeof ShellMapRoute
  ShellOverviewRoute: typeof ShellOverviewRoute
  ShellPlanVsActualRoute: typeof ShellPlanVsActualRoute
  ShellPlantPerformanceRoute: typeof ShellPlantPerformanceRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellTraceabilityRoute: typeof ShellTraceabilityRoute
  ShellTrendsRoute: typeof ShellTrendsRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAiInsightsRoute: ShellAiInsightsRoute,
  ShellAttainmentMatrixRoute: ShellAttainmentMatrixRoute,
  ShellGapRecoveryRoute: ShellGapRecoveryRoute,
  ShellLeaderboardRoute: ShellLeaderboardRoute,
  ShellMapRoute: ShellMapRoute,
  ShellOverviewRoute: ShellOverviewRoute,
  ShellPlanVsActualRoute: ShellPlanVsActualRoute,
  ShellPlantPerformanceRoute: ShellPlantPerformanceRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellTraceabilityRoute: ShellTraceabilityRoute,
  ShellTrendsRoute: ShellTrendsRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
